# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Shady Valley Farm, LLC'
tagline:          'Registered Dairy Quality Nigerian Dwarf Goats'
description:      'Goats for Sale'
url:              http://www.shadyvalleyfarm.com/
baseurl:          /

author:
  name:           'Shady Valley Farm, LLC'
  url:            http://www.shadyvalleyfarm.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
